- name: Créer le secret cloudflare-api-token-secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'roles/cert_manager/files/cloudflare-secret.yaml') | from_yaml }}"

- name: Déployer le ClusterIssuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-dns
      spec:
        acme:
          email: "{{ lookup('env', 'CLOUDFLARE_EMAIL') }}"
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-dns
          solvers:
            - dns01:
                cloudflare:
                  email: "{{ lookup('env', 'CLOUDFLARE_EMAIL') }}"
                  apiTokenSecretRef:
                    name: cloudflare-api-token-secret
                    key: api-token
