---
# playbooks/site.yml
# Playbook principal pour provisionner une VM DevOps + Kubernetes
- name: Bootstrap DevOps
  import_playbook: 01-bootstrap-devops.yml
- name: 02-infra_containerd.yml
  import_playbook: 02-infra_containerd.yml
- name: 03-kubernetes.yml
  import_playbook: 03-kubernetes.yml
- name: 03-B-k8s-users.yml
  import_playbook: 03-B-k8s-users.yml
