audit_policy_path: /etc/kubernetes/audit-policy.yaml
audit_log_dir: /var/log/kubernetes
audit_log_file: "{{ audit_log_dir }}/audit.log"

audit_log_maxage: "30"
audit_log_maxbackup: "10"
audit_log_maxsize: "100"

audit_log_level: Metadata
