---
# Playbook d'orchestration pour le bastion
# Il encha√Æne les sous-playbooks dans l'ordre

- import_playbook: 00-pebootstrap.yml
- import_playbook: 001-setup-github-deploykey.yml
- import_playbook: 002-setup-github-app.yml
- import_playbook: 003-setup-github-app.yml
- import_playbook: 004-secure-ssh.yml
