---
github_app_dir: /etc/github-app
github_app_name: nudger-vm

# Chemin vers les secrets dans le repo local
github_app_secrets_dir: "{{ playbook_dir }}/../secrets"

# Fichiers secrets attendus
github_app_app_id_file: "{{ github_app_secrets_dir }}/APP_ID"
github_app_installation_id_file: "{{ github_app_secrets_dir }}/INSTALLATION_ID"
github_app_private_key_file: "{{ github_app_secrets_dir }}/nudger-vm.private-key.pem"
