# defaults/main.yml
containerd_version: "1.4.9"
containerd_bin_dir: "/usr/local/bin"
containerd_config_dir: "/etc/containerd"
containerd_sysctl_params:
  net.ipv4.ip_forward: "1"
  net.bridge.bridge-nf-call-iptables: "1"
containerd_kubeconfig_admin_path: "/etc/kubernetes/admin.conf"
